GPUGraphLayout: RPGraph::CPUForceAtlas2 Class Reference
RPGraph::CPUForceAtlas2 Class Reference
#include <RPCPUForceAtlas2.hpp>
Public Member Functions
CPUForceAtlas2 (GraphLayout &layout, bool use_barneshut, bool strong_gravity, float gravity, float scale)
~CPUForceAtlas2 ()
void doStep () override
void sync_layout () override
Public Member Functions inherited from RPGraph::ForceAtlas2
ForceAtlas2 (GraphLayout &layout, bool use_barneshut, bool strong_gravity, float gravity, float scale)
~ForceAtlas2 ()
void doSteps (int n)
void setScale (float s)
void setGravity (float s)
float mass (nid_t n)
Public Member Functions inherited from RPGraph::LayoutAlgorithm
LayoutAlgorithm (GraphLayout &layout)
~LayoutAlgorithm ()
Private Member Functions
float swg (nid_t n)
float s (nid_t n)
float tra (nid_t n)
void rebuild_bh ()
void apply_repulsion (nid_t n)
void apply_gravity (nid_t n)
void apply_attract (nid_t n)
void updateSpeeds ()
void apply_displacement (nid_t n)
Private Attributes
Real2DVector * forces
Real2DVector * prev_forces
BarnesHutApproximator BH_Approximator
Additional Inherited Members
Public Attributes inherited from RPGraph::ForceAtlas2
bool prevent_overlap
bool use_barneshut
bool use_linlog
bool strong_gravity
Public Attributes inherited from RPGraph::LayoutAlgorithm
GraphLayout & layout
Protected Attributes inherited from RPGraph::ForceAtlas2
int iteration
float k_r
float k_g
float delta
float global_speed
float speed_efficiency
float jitter_tolerance
float k_s
float k_s_max
float theta
float epssq
float itolsq
Detailed Description
Definition at line 31 of file RPCPUForceAtlas2.hpp.
Constructor & Destructor Documentation
CPUForceAtlas2()
RPGraph::CPUForceAtlas2::CPUForceAtlas2 (GraphLayout & layout, bool use_barneshut, bool strong_gravity, float gravity, float scale)
Definition at line 40 of file RPCPUForceAtlas2.cpp.
References RPGraph::GraphLayout::getCenter(), RPGraph::GraphLayout::getSpan(), RPGraph::LayoutAlgorithm::layout, and RPGraph::ForceAtlas2::theta.
     :  ForceAtlas2(layout, use_barneshut, strong_gravity, gravity, scale),
        BH_Approximator{layout.getCenter(), layout.getSpan()+10, theta}
     {
         forces      = (Real2DVector *)malloc(sizeof(Real2DVector) * layout.graph.num_nodes());
         prev_forces = (Real2DVector *)malloc(sizeof(Real2DVector) * layout.graph.num_nodes());
         for (nid_t n = 0; n < layout.graph.num_nodes(); ++n)
         {
             forces[n]      = Real2DVector(0.0f, 0.0f);
             prev_forces[n] = Real2DVector(0.0f, 0.0f);
         }
     }
~CPUForceAtlas2()
RPGraph::CPUForceAtlas2::~CPUForceAtlas2 ()
Definition at line 55 of file RPCPUForceAtlas2.cpp.
References forces, and prev_forces.
     {
         free(forces);
         free(prev_forces);
     }
Member Function Documentation
doStep()
void RPGraph::CPUForceAtlas2::doStep () override virtual
The tip of the spear.
Implements RPGraph::ForceAtlas2.
Definition at line 249 of file RPCPUForceAtlas2.cpp.
References apply_attract(), apply_displacement(), apply_gravity(), apply_repulsion(), forces, RPGraph::GraphLayout::graph, RPGraph::ForceAtlas2::iteration, RPGraph::LayoutAlgorithm::layout, RPGraph::UGraph::num_nodes(), prev_forces, rebuild_bh(), updateSpeeds(), and RPGraph::ForceAtlas2::use_barneshut.
     {
         if (use_barneshut) rebuild_bh();
         for (nid_t n = 0; n < layout.graph.num_nodes(); ++n)
         {
             apply_gravity(n);
             apply_attract(n);
             apply_repulsion(n);
         }
         updateSpeeds();
         for (nid_t n = 0; n < layout.graph.num_nodes(); ++n)
         {
             apply_displacement(n);
             prev_forces[n]  = forces[n];
             forces[n]       = Real2DVector(0.0f, 0.0f);
         }
         iteration++;
     }
sync_layout()
void RPGraph::CPUForceAtlas2::sync_layout () override virtual
Implements RPGraph::LayoutAlgorithm.
Definition at line 271 of file RPCPUForceAtlas2.cpp.
 {}
swg()
float RPGraph::CPUForceAtlas2::swg (nid_t n) private
Eq. (8) TODO: Equation numbers from which paper?
Definition at line 137 of file RPCPUForceAtlas2.cpp.
References forces, and prev_forces.
Referenced by apply_displacement(), s(), and updateSpeeds().
     {
         return (forces[n] - prev_forces[n]).magnitude();
     }
s()
float RPGraph::CPUForceAtlas2::s (nid_t n) private
Eq. (9)
Definition at line 145 of file RPCPUForceAtlas2.cpp.
References RPGraph::ForceAtlas2::global_speed, RPGraph::ForceAtlas2::k_s, and swg().
     {
         return (k_s * global_speed)/(1.0f+global_speed*std::sqrt(swg(n)));
     }
tra()
float RPGraph::CPUForceAtlas2::tra (nid_t n) private
Eq. (12)
Definition at line 153 of file RPCPUForceAtlas2.cpp.
References forces, and prev_forces.
Referenced by updateSpeeds().
     {
         return (forces[n] + prev_forces[n]).magnitude() / 2.0;
     }
rebuild_bh()
void RPGraph::CPUForceAtlas2::rebuild_bh () private
Definition at line 235 of file RPCPUForceAtlas2.cpp.
References BH_Approximator, RPGraph::UGraph::degree(), RPGraph::GraphLayout::getCenter(), RPGraph::GraphLayout::getCoordinate(), RPGraph::GraphLayout::getSpan(), RPGraph::GraphLayout::graph, RPGraph::BarnesHutApproximator::insertParticle(), RPGraph::LayoutAlgorithm::layout, RPGraph::UGraph::num_nodes(), and RPGraph::BarnesHutApproximator::reset().
Referenced by doStep().
     {
         BH_Approximator.reset(layout.getCenter(), layout.getSpan()+10);
         for (nid_t n = 0; n < layout.graph.num_nodes(); ++n)
         {
             BH_Approximator.insertParticle(layout.getCoordinate(n),
                                            layout.graph.degree(n)+1);
         }
     }
apply_repulsion()
void RPGraph::CPUForceAtlas2::apply_repulsion (nid_t n) private
Definition at line 91 of file RPCPUForceAtlas2.cpp.
References RPGraph::BarnesHutApproximator::approximateForce(), BH_Approximator, RPGraph::distance(), forces, RPGraph::GraphLayout::getCoordinate(), RPGraph::GraphLayout::getDistance(), RPGraph::GraphLayout::getDistanceVector(), RPGraph::GraphLayout::graph, RPGraph::ForceAtlas2::k_r, RPGraph::LayoutAlgorithm::layout, RPGraph::ForceAtlas2::mass(), RPGraph::UGraph::num_nodes(), RPGraph::ForceAtlas2::theta, and RPGraph::ForceAtlas2::use_barneshut.
Referenced by doStep().
     {
         // Approximation, only for we are using.
         if (use_barneshut)
         {
             forces[n] += (BH_Approximator.approximateForce(layout.getCoordinate(n), mass(n), theta) * k_r);
         }
         else
         {
             for (nid_t t = 0; t < layout.graph.num_nodes(); ++t)
             {
                 if (n == t) continue;
                 float  distance = layout.getDistance(n, t);
                 float f_r = distance == 0.0 ? std::numeric_limits<float>::max() : k_r * mass(n) * mass(t) / distance / distance;
                 forces[n] += layout.getDistanceVector(n, t) * f_r;
             }
         }
     }
apply_gravity()
void RPGraph::CPUForceAtlas2::apply_gravity (nid_t n) private
Definition at line 111 of file RPCPUForceAtlas2.cpp.
References forces, RPGraph::GraphLayout::getX(), RPGraph::GraphLayout::getY(), RPGraph::ForceAtlas2::k_g, RPGraph::LayoutAlgorithm::layout, RPGraph::ForceAtlas2::mass(), and RPGraph::ForceAtlas2::strong_gravity.
Referenced by doStep().
     {
         float f_g, d;
         // `d' is the distance from `n' to the center (0.0, 0.0)
         d = std::sqrt(layout.getX(n)*layout.getX(n) + layout.getY(n)*layout.getY(n));
         if(d == 0.0) return;
         // Here we define the magnitude of the gravitational force `f_g'.
         if (strong_gravity)
         {
             f_g = k_g*mass(n);
         }
         else
         {
             f_g = k_g*mass(n) / d;
         }
         forces[n] += (Real2DVector(-layout.getX(n), -layout.getY(n)) * f_g);
     }
apply_attract()
void RPGraph::CPUForceAtlas2::apply_attract (nid_t n) private
Definition at line 61 of file RPCPUForceAtlas2.cpp.
References forces, RPGraph::GraphLayout::getDistance(), RPGraph::GraphLayout::getDistanceVector(), RPGraph::GraphLayout::graph, RPGraph::LayoutAlgorithm::layout, RPGraph::UGraph::neighbors_with_geq_id(), and RPGraph::ForceAtlas2::use_linlog.
Referenced by doStep().
     {
         Real2DVector f = Real2DVector(0.0, 0.0);
         for (nid_t t : layout.graph.neighbors_with_geq_id(n))
         {
             // Here we define the magnitude of the attractive force `f_a'
             // *divided* by the length distance between `n' and `t', i.e. `f_a_over_d'
             float f_a_over_d;
             if (use_linlog)
             {
                 float dist = layout.getDistance(n, t);
                 f_a_over_d = dist == 0.0 ? std::numeric_limits<float>::max() : logf(1+dist) / dist;
             }
             else
             {
                 f_a_over_d = 1.0;
             }
             f += layout.getDistanceVector(n, t) * f_a_over_d;
             //TODO: this is temporary, but required due to
             //      iteration over neighbors_with_geq_id
             forces[t] += layout.getDistanceVector(n, t) * (-f_a_over_d);
     //            forces[n] += getNormalizedDistanceVector(n, t) * f_a(n, t);
         }
         forces[n] += f;
     }
updateSpeeds()
void RPGraph::CPUForceAtlas2::updateSpeeds () private
Implementation based on Gephis java implementation.
TODO: Do we need to concern ourselves with jitter tolerance?
Definition at line 161 of file RPCPUForceAtlas2.cpp.
References RPGraph::ForceAtlas2::global_speed, RPGraph::GraphLayout::graph, RPGraph::ForceAtlas2::jitter_tolerance, RPGraph::ForceAtlas2::k_s_max, RPGraph::LayoutAlgorithm::layout, RPGraph::ForceAtlas2::mass(), RPGraph::UGraph::num_nodes(), RPGraph::ForceAtlas2::speed_efficiency, swg(), and tra().
Referenced by doStep().
     {
         // The following speed-update procedure for ForceAtlas2 follows
         // the one by Gephi:
         // https://github.com/gephi/gephi/blob/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/ForceAtlas2.java
         // `Auto adjust speeds'
         float total_swinging = 0.0;
         float total_effective_traction = 0.0;
         for (nid_t nid = 0; nid < layout.graph.num_nodes(); ++nid)
         {
             total_swinging += mass(nid) * swg(nid); // Eq. (11)
             total_effective_traction += mass(nid) * tra(nid); // Eq. (13)
         }
         //We want to find the right jitter tollerance for this graph,
         // such that totalSwinging < tolerance * totalEffectiveTraction
         float estimated_optimal_jitter_tollerance = 0.05 * std::sqrt(layout.graph.num_nodes());
         float minJT = std::sqrt(estimated_optimal_jitter_tollerance);
         float jt = jitter_tolerance * fmaxf(minJT,
                                            fminf(k_s_max,
                                                  estimated_optimal_jitter_tollerance * total_effective_traction / powf(layout.graph.num_nodes(), 2.0)
                                                  )
                                            );
         float min_speed_efficiency = 0.05;
         // `Protect against erratic behavior'
         if (total_swinging / total_effective_traction > 2.0)
         {
             if (speed_efficiency > min_speed_efficiency) speed_efficiency *= 0.5;
             jt = fmaxf(jt, jitter_tolerance);
         }
         // `Speed efficiency is how the speed really corrosponds to the swinging vs. convergence tradeoff.'
         // `We adjust it slowly and carefully'
         float targetSpeed = jt * speed_efficiency * total_effective_traction / total_swinging;
         if (total_swinging > jt * total_effective_traction)
         {
             if (speed_efficiency > min_speed_efficiency)
             {
                 speed_efficiency *= 0.7;
             }
         }
         else if (global_speed < 1000)
         {
             speed_efficiency *= 1.3;
         }
         // `But the speed shouldn't rise much too quickly, ... would make convergence drop dramatically'.
         float max_rise = 0.5;
         global_speed += fminf(targetSpeed - global_speed, max_rise * global_speed);
     }
apply_displacement()
void RPGraph::CPUForceAtlas2::apply_displacement (nid_t n) private
Definition at line 219 of file RPCPUForceAtlas2.cpp.
References forces, RPGraph::ForceAtlas2::global_speed, RPGraph::LayoutAlgorithm::layout, RPGraph::GraphLayout::moveNode(), RPGraph::ForceAtlas2::prevent_overlap, and swg().
Referenced by doStep().
     {
         if (prevent_overlap)
         {
             // Not yet implemented
             exit(EXIT_FAILURE);
         }
         else
         {
             float factor = global_speed / (1.0 + std::sqrt(global_speed * swg(n)));
             layout.moveNode(n, forces[n] * factor);
         }
     }
Member Data Documentation
forces
Real2DVector* RPGraph::CPUForceAtlas2::forces private
Definition at line 41 of file RPCPUForceAtlas2.hpp.
Referenced by apply_attract(), apply_displacement(), apply_gravity(), apply_repulsion(), doStep(), swg(), tra(), and ~CPUForceAtlas2().
prev_forces
Real2DVector * RPGraph::CPUForceAtlas2::prev_forces private
Definition at line 41 of file RPCPUForceAtlas2.hpp.
Referenced by doStep(), swg(), tra(), and ~CPUForceAtlas2().
BH_Approximator
BarnesHutApproximator RPGraph::CPUForceAtlas2::BH_Approximator private
Definition at line 42 of file RPCPUForceAtlas2.hpp.
Referenced by apply_repulsion(), and rebuild_bh().
The documentation for this class was generated from the following files:
src/RPCPUForceAtlas2.hpp
src/RPCPUForceAtlas2.cpp