GPUGraphLayout: RPGraph::GraphLayout Class Reference
RPGraph::GraphLayout Class Reference
#include <RPGraphLayout.hpp>
Public Member Functions
GraphLayout (RPGraph::UGraph &graph, float width=10000, float height=10000)
~GraphLayout ()
void randomizePositions ()
float getX (nid_t node_id)
float getY (nid_t node_id)
float getXRange ()
float getYRange ()
float getSpan ()
float getDistance (nid_t n1, nid_t n2)
Real2DVector getDistanceVector (nid_t n1, nid_t n2)
Real2DVector getNormalizedDistanceVector (nid_t n1, nid_t n2)
Coordinate getCoordinate (nid_t node_id)
Coordinate getCenter ()
void setX (nid_t node_id, float x_value)
void setY (nid_t node_id, float y_value)
void moveNode (nid_t, Real2DVector v)
void setCoordinates (nid_t node_id, Coordinate c)
void writeToPNG (const int image_w, const int image_h, std::string path)
void writeToCSV (std::string path)
void writeToBin (std::string path)
Public Attributes
UGraph & graph
Protected Member Functions
float minX ()
float minY ()
float maxX ()
float maxY ()
Protected Attributes
float width
float height
Private Attributes
Coordinate * coordinates
Detailed Description
Definition at line 35 of file RPGraphLayout.hpp.
Constructor & Destructor Documentation
GraphLayout()
RPGraph::GraphLayout::GraphLayout (RPGraph::UGraph & graph, float width = 10000, float height = 10000)
Mallocs an array for the coordinates. width and height default to 10,000
Q: What are width and height for? Size of image?
Definition at line 45 of file RPGraphLayout.cpp.
         : graph(graph), width(width), height(height)
     {
         // Mem complexity: O(|V|)
         coordinates = (Coordinate *) malloc(graph.num_nodes() * sizeof(Coordinate));
     }
References coordinates, graph, and RPGraph::UGraph::num_nodes().
~GraphLayout()
RPGraph::GraphLayout::~GraphLayout ()
Definition at line 52 of file RPGraphLayout.cpp.
     {
         free(coordinates);
     }
References coordinates.
Member Function Documentation
minX()
float RPGraph::GraphLayout::minX () protected
Find: getXRange: only this file, getSpan, getCenter, writePng getYRange: only this file getCenter: RPCPUForceAtlas2.cpp, not important
Definition at line 88 of file RPGraphLayout.cpp.
     {
         float minX = std::numeric_limits<float>::max();
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
             if (getX(n) < minX) minX = getX(n);
         return minX;
     }
References getX(), graph, and RPGraph::UGraph::num_nodes().
Referenced by getCenter(), getXRange(), and writeToPNG().
minY()
float RPGraph::GraphLayout::minY () protected
Definition at line 104 of file RPGraphLayout.cpp.
     {
         float minY = std::numeric_limits<float>::max();
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
             if (getY(n) < minY) minY = getY(n);
         return minY;
     }
References getY(), graph, and RPGraph::UGraph::num_nodes().
Referenced by getCenter(), getYRange(), and writeToPNG().
maxX()
float RPGraph::GraphLayout::maxX () protected
Definition at line 96 of file RPGraphLayout.cpp.
     {
         float maxX = std::numeric_limits<float>::min();
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
             if (getX(n) > maxX) maxX = getX(n);
         return maxX;
     }
References getX(), graph, and RPGraph::UGraph::num_nodes().
Referenced by getXRange().
maxY()
float RPGraph::GraphLayout::maxY () protected
Definition at line 112 of file RPGraphLayout.cpp.
     {
         float maxY = std::numeric_limits<float>::min();
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
             if (getY(n) > maxY) maxY = getY(n);
         return maxY;
     }
References getY(), graph, and RPGraph::UGraph::num_nodes().
Referenced by getYRange().
randomizePositions()
void RPGraph::GraphLayout::randomizePositions ()
TODO: Modify this bit when using communities to randomize node positions within some delta of the community position in the community layout that was produced originally. NOTE: Keep original for laying out the community graph.
Definition at line 57 of file RPGraphLayout.cpp.
     {
         for (nid_t i = 0; i <  graph.num_nodes(); ++i)
         {
             setX(i, get_random(-width/2.0, width/2.0));
             setY(i, get_random(-height/2.0, height/2.0));
         }
     }
References RPGraph::get_random(), graph, height, RPGraph::UGraph::num_nodes(), setX(), setY(), and width.
getX()
float RPGraph::GraphLayout::getX (nid_t node_id)
Definition at line 72 of file RPGraphLayout.cpp.
     {
         return coordinates[node_id].x;
     }
References coordinates, and RPGraph::Coordinate::x.
Referenced by RPGraph::CPUForceAtlas2::apply_gravity(), getDistance(), getDistanceVector(), getNormalizedDistanceVector(), maxX(), minX(), moveNode(), writeToBin(), writeToCSV(), and writeToPNG().
getY()
float RPGraph::GraphLayout::getY (nid_t node_id)
Definition at line 77 of file RPGraphLayout.cpp.
     {
         return coordinates[node_id].y;
     }
References coordinates, and RPGraph::Coordinate::y.
Referenced by RPGraph::CPUForceAtlas2::apply_gravity(), getDistance(), getDistanceVector(), getNormalizedDistanceVector(), maxY(), minY(), moveNode(), writeToBin(), writeToCSV(), and writeToPNG().
getXRange()
float RPGraph::GraphLayout::getXRange ()
Definition at line 120 of file RPGraphLayout.cpp.
     {
         return maxX()- minX();
     }
References maxX(), and minX().
Referenced by getCenter(), getSpan(), and writeToPNG().
getYRange()
float RPGraph::GraphLayout::getYRange ()
Definition at line 125 of file RPGraphLayout.cpp.
     {
         return maxY() - minY();
     }
References maxY(), and minY().
Referenced by getCenter(), getSpan(), and writeToPNG().
getSpan()
float RPGraph::GraphLayout::getSpan ()
Definition at line 130 of file RPGraphLayout.cpp.
     {
         return ceil(fmaxf(getXRange(), getYRange()));
     }
References getXRange(), and getYRange().
Referenced by RPGraph::CPUForceAtlas2::CPUForceAtlas2(), and RPGraph::CPUForceAtlas2::rebuild_bh().
getDistance()
float RPGraph::GraphLayout::getDistance (nid_t n1, nid_t n2)
Usage? CPU FA2 only.
What
Definition at line 140 of file RPGraphLayout.cpp.
     {
         const float dx = getX(n1)-getX(n2);
         const float dy = getY(n1)-getY(n2);
         return std::sqrt(dx*dx + dy*dy);
     }
References getX(), and getY().
Referenced by RPGraph::CPUForceAtlas2::apply_attract(), and RPGraph::CPUForceAtlas2::apply_repulsion().
getDistanceVector()
Real2DVector RPGraph::GraphLayout::getDistanceVector (nid_t n1, nid_t n2)
Which of these 2 are used? Vectors are used in CPU FA2 implementation.
Definition at line 151 of file RPGraphLayout.cpp.
     {
         return Real2DVector(getX(n2) - getX(n1), getY(n2) - getY(n1));
     }
References getX(), and getY().
Referenced by RPGraph::CPUForceAtlas2::apply_attract(), and RPGraph::CPUForceAtlas2::apply_repulsion().
getNormalizedDistanceVector()
Real2DVector RPGraph::GraphLayout::getNormalizedDistanceVector (nid_t n1, nid_t n2)
Make that which of these 3 are used? IRRELEVANT: Commented out in CPU FA2 only.
Definition at line 159 of file RPGraphLayout.cpp.
     {
         const float x1 = getX(n1);
         const float x2 = getX(n2);
         const float y1 = getY(n1);
         const float y2 = getY(n2);
         const float dx = x2 - x1;
         const float dy = y2 - y1;
         const float len = std::sqrt(dx*dx + dy*dy);
         return Real2DVector(dx / len, dy / len);
     }
References getX(), and getY().
getCoordinate()
Coordinate RPGraph::GraphLayout::getCoordinate (nid_t node_id)
Indexes into coordinates array. node_id MUST be mapped through the associated UGraph object.
TODO: Should we map through the associated UGraph by default? Or is that to much overhead? Or should this be a private field with friend specification for classes that need it, and we can overload it for the public interface?
Definition at line 177 of file RPGraphLayout.cpp.
     {
         return coordinates[node_id];
     }
References coordinates.
Referenced by RPGraph::CPUForceAtlas2::apply_repulsion(), and RPGraph::CPUForceAtlas2::rebuild_bh().
getCenter()
Coordinate RPGraph::GraphLayout::getCenter ()
Usage: pngwriter only.
Definition at line 185 of file RPGraphLayout.cpp.
     {
         float x = minX() + getXRange()/2.0;
         float y = minY() + getYRange()/2.0;
         return Coordinate(x, y);
     }
References getXRange(), getYRange(), minX(), and minY().
Referenced by RPGraph::CPUForceAtlas2::CPUForceAtlas2(), RPGraph::CPUForceAtlas2::rebuild_bh(), and writeToPNG().
setX()
void RPGraph::GraphLayout::setX (nid_t node_id, float x_value)
Updates x in coordinates array.
Definition at line 195 of file RPGraphLayout.cpp.
     {
         coordinates[node_id].x = x_value;
     }
References coordinates, and RPGraph::Coordinate::x.
Referenced by moveNode(), randomizePositions(), and setCoordinates().
setY()
void RPGraph::GraphLayout::setY (nid_t node_id, float y_value)
Definition at line 200 of file RPGraphLayout.cpp.
     {
         coordinates[node_id].y = y_value;
     }
References coordinates, and RPGraph::Coordinate::y.
Referenced by moveNode(), randomizePositions(), and setCoordinates().
moveNode()
void RPGraph::GraphLayout::moveNode (nid_t n, RPGraph::Real2DVector v)
Why is move only used with a 2DVector?
Definition at line 208 of file RPGraphLayout.cpp.
     {
         setX(n, getX(n) + v.x);
         setY(n, getY(n) + v.y);
     }
References getX(), getY(), setX(), setY(), RPGraph::Real2DVector::x, and RPGraph::Real2DVector::y.
Referenced by RPGraph::CPUForceAtlas2::apply_displacement().
setCoordinates()
void RPGraph::GraphLayout::setCoordinates (nid_t node_id, Coordinate c)
Never used. Why not? TODO: We will probably use this and maybe the moveNode function to specify our layout after
Definition at line 218 of file RPGraphLayout.cpp.
     {
         setX(node_id, c.x);
         setY(node_id, c.y);
     }
References setX(), setY(), RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by main().
writeToPNG()
void RPGraph::GraphLayout::writeToPNG (const int image_w, const int image_h, std::string path)
pngwriter entry point.
TODO: Adjust node opacity for best results.
Definition at line 227 of file RPGraphLayout.cpp.
     {
         const float xRange = getXRange();
         const float yRange = getYRange();
         const RPGraph::Coordinate center = getCenter(); // Why do we need the center?
         const float xCenter = center.x; // Probably to set the origin for layout.
         const float yCenter = center.y;
         const float minX = xCenter - xRange/2.0;
         const float minY = yCenter - yRange/2.0;
         const float xScale = image_w/xRange;
         const float yScale = image_h/yRange;
         // Here we need to do some guessing as to what the optimal
         // opacity of nodes and edges might be, given network size.
         const float node_opacity = 10000.0  / graph.num_nodes();
         const float edge_opacity = 100000.0 / graph.num_edges();
         // Write to file.
         pngwriter layout_png(image_w, image_h, 0, path.c_str());
         layout_png.invert(); // set bg. to white
         for (nid_t n1 = 0; n1 < graph.num_nodes(); ++n1)
         {
             // Plot node,
             layout_png.filledcircle_blend((getX(n1) - minX)*xScale,
                                           (getY(n1) - minY)*yScale,
                                           3, node_opacity, 0, 0, 0);
             for (nid_t n2 : graph.neighbors_with_geq_id(n1)) {
                 // ... and edge.
                 layout_png.line_blend((getX(n1) - minX)*xScale, (getY(n1) - minY)*yScale,
                                       (getX(n2) - minX)*xScale, (getY(n2) - minY)*yScale,
                                       edge_opacity, 0, 0, 0);
             }
         }
         // Write it to disk.
         layout_png.write_png();
     }
References getCenter(), getX(), getXRange(), getY(), getYRange(), graph, minX(), minY(), RPGraph::UGraph::neighbors_with_geq_id(), RPGraph::UGraph::num_edges(), RPGraph::UGraph::num_nodes(), RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by main().
writeToCSV()
void RPGraph::GraphLayout::writeToCSV (std::string path)
Writing to csv may be a good way to streamline testing the decompressions effectiveness. NOTE: There is no loadFromCSV method. Would go in this file.
Definition at line 273 of file RPGraphLayout.cpp.
     {
         if (is_file_exists(path.c_str()))
         {
             printf("Error: File exists at %s\n", path.c_str());
             exit(EXIT_FAILURE);
         }
         std::ofstream out_file(path);
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
         {
             nid_t id = graph.node_map_r[n]; // id as found in edgelist
             out_file << id << "," << getX(n) << "," << getY(n) << "\n";
         }
         out_file.close();
     }
References getX(), getY(), graph, is_file_exists(), RPGraph::UGraph::node_map_r, and RPGraph::UGraph::num_nodes().
Referenced by main().
writeToBin()
void RPGraph::GraphLayout::writeToBin (std::string path)
Do we have any use for writing to bin?
Definition at line 295 of file RPGraphLayout.cpp.
     {
         if (is_file_exists(path.c_str()))
         {
             printf("Error: File exists at %s\n", path.c_str());
             exit(EXIT_FAILURE);
         }
         std::ofstream out_file(path, std::ofstream::binary);
         for (nid_t n = 0; n < graph.num_nodes(); ++n)
         {
             nid_t id = graph.node_map_r[n]; // id as found in edgelist
             float x = getX(n);
             float y = getY(n);
             out_file.write(reinterpret_cast<const char*>(&id), sizeof(id));
             out_file.write(reinterpret_cast<const char*>(&x), sizeof(x));
             out_file.write(reinterpret_cast<const char*>(&y), sizeof(y));
         }
         out_file.close();
     }
References getX(), getY(), graph, is_file_exists(), RPGraph::UGraph::node_map_r, and RPGraph::UGraph::num_nodes().
Referenced by main().
Member Data Documentation
coordinates
Coordinate* RPGraph::GraphLayout::coordinates private
Definition at line 38 of file RPGraphLayout.hpp.
Referenced by getCoordinate(), getX(), getY(), GraphLayout(), setX(), setY(), and ~GraphLayout().
width
float RPGraph::GraphLayout::width protected
Definition at line 41 of file RPGraphLayout.hpp.
Referenced by randomizePositions().
height
float RPGraph::GraphLayout::height protected
Definition at line 41 of file RPGraphLayout.hpp.
Referenced by randomizePositions().
graph
UGraph& RPGraph::GraphLayout::graph
Definition at line 49 of file RPGraphLayout.hpp.
Referenced by RPGraph::CPUForceAtlas2::apply_attract(), RPGraph::CPUForceAtlas2::apply_repulsion(), RPGraph::CPUForceAtlas2::doStep(), GraphLayout(), RPGraph::ForceAtlas2::mass(), maxX(), maxY(), minX(), minY(), randomizePositions(), RPGraph::CPUForceAtlas2::rebuild_bh(), RPGraph::CPUForceAtlas2::updateSpeeds(), writeToBin(), writeToCSV(), and writeToPNG().
The documentation for this class was generated from the following files:
src/RPGraphLayout.hpp
src/RPGraphLayout.cpp