GPUGraphLayout: RPGraph::UGraph Class Reference
RPGraph::UGraph Class Reference
#include <RPGraph.hpp>
Public Member Functions
UGraph (std::string edgelist_path)
virtual nid_t num_nodes () override
virtual nid_t num_edges () override
virtual nid_t degree (nid_t nid) override
virtual nid_t in_degree (nid_t nid) override
virtual nid_t out_degree (nid_t nid) override
std::vector< nid_t > neighbors_with_geq_id (nid_t nid) override
Public Attributes
std::unordered_map< nid_t, nid_t > node_map
std::unordered_map< nid_t, nid_t > node_map_r
Private Member Functions
bool has_node (nid_t nid)
bool has_edge (nid_t s, nid_t t)
void add_node (nid_t nid)
void add_edge (nid_t s, nid_t t)
Private Attributes
nid_t node_count
nid_t edge_count
std::unordered_map< nid_t, nid_t > degrees
std::unordered_map< nid_t, std::vector< nid_t > > adjacency_list
Detailed Description
Definition at line 55 of file RPGraph.hpp.
Constructor & Destructor Documentation
UGraph()
RPGraph::UGraph::UGraph (std::string edgelist_path)
Used once in main file (graph_viewer.cpp)
Definition at line 40 of file RPGraph.cpp.
References add_edge(), edge_count, has_edge(), and node_count.
     {
         node_count = 0;
         edge_count = 0;
         std::fstream edgelist_file(edgelist_path, std::ifstream::in);
         std::string line;
         while(std::getline(edgelist_file, line))
         {
             // Skip any comments
             if(line[0] == '#') continue;
             // Read source and target from file
             nid_t s, t;
             std::istringstream(line) >> s >> t;
             if(s != t and !has_edge(s, t)) add_edge(s, t);
         }
         edgelist_file.close();
     }
Member Function Documentation
has_node()
bool RPGraph::UGraph::has_node (nid_t nid) private
Definition at line 63 of file RPGraph.cpp.
References node_map.
Referenced by add_edge(), add_node(), and has_edge().
     {
         return node_map.count(nid) > 0;
     }
has_edge()
bool RPGraph::UGraph::has_edge (nid_t s, nid_t t) private
Definition at line 68 of file RPGraph.cpp.
References adjacency_list, has_node(), and node_map.
Referenced by add_edge(), and UGraph().
     {
         if(!has_node(s) or !has_node(t)) return false;
         nid_t s_mapped = node_map[s];
         nid_t t_mapped = node_map[t];
         if(adjacency_list.count(std::min(s_mapped, t_mapped)) == 0) return false;
         std::vector<nid_t> neighbors = adjacency_list[std::min(s_mapped, t_mapped)];
         if(std::find(neighbors.begin(), neighbors.end(), std::max(s_mapped, t_mapped)) == neighbors.end())
             return false;
         else
             return true;
     }
add_node()
void RPGraph::UGraph::add_node (nid_t nid) private
Definition at line 84 of file RPGraph.cpp.
References has_node(), node_count, node_map, and node_map_r.
Referenced by add_edge().
     {
         if(!has_node(nid))
         {
             node_map[nid] = node_count;
             node_map_r[node_count] = nid;
             node_count++;
         }
     }
add_edge()
void RPGraph::UGraph::add_edge (nid_t s, nid_t t) private
Definition at line 94 of file RPGraph.cpp.
References add_node(), adjacency_list, degrees, edge_count, has_edge(), has_node(), and node_map.
Referenced by UGraph().
     {
         if(has_edge(s, t)) return;
         if(!has_node(s)) add_node(s);
         if(!has_node(t)) add_node(t);
         nid_t s_mapped = node_map[s];
         nid_t t_mapped = node_map[t];
         // Insert edge into adjacency_list
         adjacency_list[std::min(s_mapped, t_mapped)].push_back(std::max(s_mapped, t_mapped));
         degrees[s_mapped] += 1;
         degrees[t_mapped] += 1;
         edge_count++;
     }
num_nodes()
nid_t RPGraph::UGraph::num_nodes () override virtual
Implements RPGraph::Graph.
Definition at line 109 of file RPGraph.cpp.
References node_count.
Referenced by RPGraph::CPUForceAtlas2::apply_repulsion(), RPGraph::CPUForceAtlas2::doStep(), RPGraph::GraphLayout::GraphLayout(), main(), RPGraph::GraphLayout::maxX(), RPGraph::GraphLayout::maxY(), RPGraph::GraphLayout::minX(), RPGraph::GraphLayout::minY(), RPGraph::GraphLayout::randomizePositions(), RPGraph::CPUForceAtlas2::rebuild_bh(), RPGraph::CPUForceAtlas2::updateSpeeds(), RPGraph::GraphLayout::writeToBin(), RPGraph::GraphLayout::writeToCSV(), and RPGraph::GraphLayout::writeToPNG().
     {
         return node_count;
     }
num_edges()
nid_t RPGraph::UGraph::num_edges () override virtual
Implements RPGraph::Graph.
Definition at line 114 of file RPGraph.cpp.
References edge_count.
Referenced by main(), and RPGraph::GraphLayout::writeToPNG().
     {
         return edge_count;
     }
degree()
nid_t RPGraph::UGraph::degree (nid_t nid) override virtual
Implements RPGraph::Graph.
Definition at line 119 of file RPGraph.cpp.
References degrees.
Referenced by in_degree(), RPGraph::ForceAtlas2::mass(), out_degree(), and RPGraph::CPUForceAtlas2::rebuild_bh().
     {
         return degrees[nid];
     }
in_degree()
nid_t RPGraph::UGraph::in_degree (nid_t nid) override virtual
Implements RPGraph::Graph.
Definition at line 124 of file RPGraph.cpp.
References degree().
     {
         return degree(nid);
     }
out_degree()
nid_t RPGraph::UGraph::out_degree (nid_t nid) override virtual
Implements RPGraph::Graph.
Definition at line 129 of file RPGraph.cpp.
References degree().
     {
         return degree(nid);
     }
neighbors_with_geq_id()
std::vector< nid_t > RPGraph::UGraph::neighbors_with_geq_id (nid_t nid) override virtual
Implements RPGraph::Graph.
Definition at line 133 of file RPGraph.cpp.
References adjacency_list.
Referenced by RPGraph::CPUForceAtlas2::apply_attract(), and RPGraph::GraphLayout::writeToPNG().
     {
         return adjacency_list[nid];
     }
Member Data Documentation
node_count
nid_t RPGraph::UGraph::node_count private
Definition at line 58 of file RPGraph.hpp.
Referenced by add_node(), num_nodes(), and UGraph().
edge_count
nid_t RPGraph::UGraph::edge_count private
Definition at line 58 of file RPGraph.hpp.
Referenced by add_edge(), num_edges(), and UGraph().
degrees
std::unordered_map<nid_t, nid_t> RPGraph::UGraph::degrees private
Definition at line 59 of file RPGraph.hpp.
Referenced by add_edge(), and degree().
adjacency_list
std::unordered_map<nid_t, std::vector<nid_t> > RPGraph::UGraph::adjacency_list private
Definition at line 60 of file RPGraph.hpp.
Referenced by add_edge(), has_edge(), and neighbors_with_geq_id().
node_map
std::unordered_map<nid_t, nid_t> RPGraph::UGraph::node_map
Definition at line 71 of file RPGraph.hpp.
Referenced by add_edge(), add_node(), has_edge(), and has_node().
node_map_r
std::unordered_map<nid_t, nid_t> RPGraph::UGraph::node_map_r
Definition at line 72 of file RPGraph.hpp.
Referenced by add_node(), RPGraph::GraphLayout::writeToBin(), and RPGraph::GraphLayout::writeToCSV().
The documentation for this class was generated from the following files:
src/RPGraph.hpp
src/RPGraph.cpp