GPUGraphLayout: RPGraph::BarnesHutApproximator Class Reference
RPGraph::BarnesHutApproximator Class Reference
#include <RPBarnesHutApproximator.hpp>
Public Member Functions
BarnesHutApproximator (Coordinate root_center, float root_length, float theta)
Real2DVector approximateForce (Coordinate particle_pos, float particle_mass, float theta)
void insertParticle (Coordinate particle_position, float particle_mass)
void reset (Coordinate root_center, float root_length)
void setTheta (float theta)
Private Attributes
BarnesHutCell * root_cell = nullptr
const float theta
Coordinate root_center
float root_length
Detailed Description
Definition at line 56 of file RPBarnesHutApproximator.hpp.
Constructor & Destructor Documentation
BarnesHutApproximator()
RPGraph::BarnesHutApproximator::BarnesHutApproximator (Coordinate root_center, float root_length, float theta)
Constructor that calls reset.
Definition at line 67 of file RPBarnesHutApproximator.cpp.
     : root_center{root_center}, root_length{root_length}, theta{theta}
     {
         this->reset(root_center, root_length);
     }
References root_center.
Member Function Documentation
approximateForce()
Real2DVector RPGraph::BarnesHutApproximator::approximateForce (Coordinate particle_pos, float particle_mass, float theta)
Definition at line 86 of file RPBarnesHutApproximator.cpp.
     {
         Real2DVector force = Real2DVector(0.0, 0.0);
         std::queue<BarnesHutCell*> cells_to_check;
         cells_to_check.push(root_cell);
         BarnesHutCell *cur_cell;
         while (!cells_to_check.empty())
         {
             cur_cell = cells_to_check.front();
             cells_to_check.pop();
             // TODO: Why is D2 const?
             const float D2 = distance2(particle_pos, cur_cell->mass_center);
             if (D2 == 0)
             {
                 // If we approximate the force of a particle on itself...
                 if (cur_cell->num_subparticles == 0) continue;
                 else return Real2DVector(rand(), rand());
             }
             // length / D >= theta is the criterion to divide into subcells.
             if (cur_cell->length*cur_cell->length / D2 < theta*theta || cur_cell->num_subparticles == 0)
                 force += direction(particle_pos, cur_cell->mass_center)  *
                 (particle_mass * cur_cell->total_mass / D2);
             else
                 for (int i = 0; i < 4; ++i)
                     if (cur_cell->sub_cells[i] != nullptr) cells_to_check.push(cur_cell->sub_cells[i]);
         }
         return force;
     }
References RPGraph::direction(), RPGraph::distance2(), RPGraph::BarnesHutCell::length, RPGraph::BarnesHutCell::mass_center, RPGraph::BarnesHutCell::num_subparticles, root_cell, RPGraph::BarnesHutCell::sub_cells, and RPGraph::BarnesHutCell::total_mass.
Referenced by RPGraph::CPUForceAtlas2::apply_repulsion().
insertParticle()
void RPGraph::BarnesHutApproximator::insertParticle (RPGraph::Coordinate particle_position, float particle_mass)
Definition at line 120 of file RPBarnesHutApproximator.cpp.
     {
         if(not root_cell)
         {
             root_cell = new BarnesHutCell(this->root_center, this->root_length,
                                           particle_position, particle_mass);
         }
         else
         {
             BarnesHutCell *cur_cell = root_cell;
             while (true)
             {
                 const int quadrant_new_particle = (particle_position-cur_cell->cell_center).quadrant();
                 if (particle_position.y > cur_cell->ub or particle_position.x > cur_cell->rb or
                     particle_position.x < cur_cell->lb or particle_position.y < cur_cell->bb)
                 {
                     //fprintf(stderr, "error: Barnes-Hut: Can't insert particle out of bounds of this cell.\n");
                     return;
                 }
                 // N.B. a BarnesHutCell is never empty, but can lack subparticles/cells.
                 // If so, we need to create, and insert, a subcell for the single particle that
                 // is stored in this cell.
                 if (cur_cell->num_subparticles == 0)
                 {
                     if (particle_position == cur_cell->mass_center)
                     {
                         // We want two particles in the same place...
                         // Thats equivalent to a single particle with summed masses.
                         // mass_center won't change.
                         cur_cell->total_mass += particle_mass;
                         return;
                     }
                     // We move the single particle to a subcell.
                     int quadrant_existing_particle = (cur_cell->mass_center - cur_cell->cell_center).quadrant();
                     cur_cell->add_leafcell(quadrant_existing_particle, cur_cell->total_mass, cur_cell->mass_center);
                 }
                 // We assume inserting will succeed, and update total_mass and mass_center accordingly
                 cur_cell->total_mass  += particle_mass;
                 cur_cell->mass_center  = cur_cell->mass_center * (float) (cur_cell->num_subparticles);
                 cur_cell->mass_center += particle_position;
                 cur_cell->mass_center /= (cur_cell->num_subparticles+1);
                 // If we can add a leaf-cell in an empty slot, we do so.
                 if (cur_cell->sub_cells[quadrant_new_particle] == nullptr)
                 {
                     cur_cell->add_leafcell(quadrant_new_particle, particle_mass, particle_position);
                     return;
                 }
                 // Else we recurse to the occupied cell.
                 else
                 {
                     cur_cell->num_subparticles += 1;
                     cur_cell = cur_cell->sub_cells[quadrant_new_particle];
                 }
             }
         }
     }
References RPGraph::BarnesHutCell::add_leafcell(), RPGraph::BarnesHutCell::bb, RPGraph::BarnesHutCell::cell_center, RPGraph::BarnesHutCell::lb, RPGraph::BarnesHutCell::mass_center, RPGraph::BarnesHutCell::num_subparticles, RPGraph::BarnesHutCell::rb, root_cell, root_center, root_length, RPGraph::BarnesHutCell::sub_cells, RPGraph::BarnesHutCell::total_mass, RPGraph::BarnesHutCell::ub, RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by RPGraph::CPUForceAtlas2::rebuild_bh().
reset()
void RPGraph::BarnesHutApproximator::reset (Coordinate root_center, float root_length)
Deletes the current root_cell and resets the center and length of the BHApproximator
Definition at line 76 of file RPBarnesHutApproximator.cpp.
     {
         delete root_cell; // this recursively deletes the entire tree
         root_cell = nullptr;
         this->root_center = root_center;
         this->root_length = root_length;
     }
References root_cell, root_center, and root_length.
Referenced by RPGraph::CPUForceAtlas2::rebuild_bh().
setTheta()
void RPGraph::BarnesHutApproximator::setTheta (float theta)
TODO: Why have setTheta if theta is declared const?
Member Data Documentation
root_cell
BarnesHutCell* RPGraph::BarnesHutApproximator::root_cell = nullptr private
Definition at line 67 of file RPBarnesHutApproximator.hpp.
Referenced by approximateForce(), insertParticle(), and reset().
theta
const float RPGraph::BarnesHutApproximator::theta private
Definition at line 68 of file RPBarnesHutApproximator.hpp.
root_center
Coordinate RPGraph::BarnesHutApproximator::root_center private
Definition at line 69 of file RPBarnesHutApproximator.hpp.
Referenced by BarnesHutApproximator(), insertParticle(), and reset().
root_length
float RPGraph::BarnesHutApproximator::root_length private
Definition at line 70 of file RPBarnesHutApproximator.hpp.
Referenced by insertParticle(), and reset().
The documentation for this class was generated from the following files:
src/RPBarnesHutApproximator.hpp
src/RPBarnesHutApproximator.cpp