GPUGraphLayout: RPGraph::Real2DVector Class Reference
RPGraph::Real2DVector Class Reference
#include <RPCommon.hpp>
Public Member Functions
Real2DVector (float x, float y)
float magnitude ()
float distance (Real2DVector to)
Real2DVector operator* (float b)
Real2DVector operator/ (float b)
Real2DVector operator+ (Real2DVector b)
Real2DVector operator- (Real2DVector b)
void operator+= (Real2DVector b)
Real2DVector getNormalized ()
Real2DVector normalize ()
Public Attributes
float x
float y
Detailed Description
Definition at line 51 of file RPCommon.hpp.
Constructor & Destructor Documentation
Real2DVector()
RPGraph::Real2DVector::Real2DVector (float x, float y)
Why did they have to define their own 2DVector class? Usages:
RPBarnesHutApproximater
RPCPUForceAtlas2
RPGraphLayout
Definition at line 59 of file RPCommon.cpp.
Referenced by getNormalized(), operator*(), operator+(), operator-(), and operator/().
 : x(x), y(y) {};
Member Function Documentation
magnitude()
float RPGraph::Real2DVector::magnitude ()
Definition at line 61 of file RPCommon.cpp.
References x, and y.
Referenced by getNormalized(), and normalize().
     {
         return std::sqrt(x*x + y*y);
     }
distance()
float RPGraph::Real2DVector::distance (RPGraph::Real2DVector to)
Definition at line 66 of file RPCommon.cpp.
References x, and y.
     {
         const float dx = (x - to.x)*(x - to.x);
         const float dy = (y - to.y)*(y - to.y);
         return std::sqrt(dx*dx + dy*dy);
     }
operator*()
Real2DVector RPGraph::Real2DVector::operator* (float b)
Definition at line 74 of file RPCommon.cpp.
References Real2DVector(), x, and y.
     {
         return Real2DVector(this->x * b, this->y * b);
     }
operator/()
Real2DVector RPGraph::Real2DVector::operator/ (float b)
Definition at line 79 of file RPCommon.cpp.
References Real2DVector(), x, and y.
     {
         return Real2DVector(this->x / b, this->y / b);
     }
operator+()
Real2DVector RPGraph::Real2DVector::operator+ (Real2DVector b)
Definition at line 85 of file RPCommon.cpp.
References Real2DVector(), x, and y.
     {
         return Real2DVector(this->x + b.x, this->y + b.y);
     }
operator-()
Real2DVector RPGraph::Real2DVector::operator- (Real2DVector b)
Definition at line 91 of file RPCommon.cpp.
References Real2DVector(), x, and y.
     {
         return Real2DVector(this->x - b.x, this->y - b.y);
     }
operator+=()
void RPGraph::Real2DVector::operator+= (Real2DVector b)
Definition at line 96 of file RPCommon.cpp.
References x, and y.
     {
         this->x += b.x;
         this->y += b.y;
     }
getNormalized()
Real2DVector RPGraph::Real2DVector::getNormalized ()
Definition at line 102 of file RPCommon.cpp.
References magnitude(), Real2DVector(), x, and y.
     {
         return Real2DVector(this->x / magnitude(), this->y / magnitude());
     }
normalize()
Real2DVector RPGraph::Real2DVector::normalize ()
Definition at line 107 of file RPCommon.cpp.
References magnitude(), x, and y.
     {
         const float m = magnitude();
         this->x /= m;
         this->y /= m;
         return *this;
     }
Member Data Documentation
x
float RPGraph::Real2DVector::x
Definition at line 55 of file RPCommon.hpp.
Referenced by distance(), getNormalized(), magnitude(), RPGraph::GraphLayout::moveNode(), normalize(), operator*(), operator+(), RPGraph::Coordinate::operator+(), operator+=(), RPGraph::Coordinate::operator+=(), operator-(), and operator/().
y
float RPGraph::Real2DVector::y
Definition at line 55 of file RPCommon.hpp.
Referenced by distance(), getNormalized(), magnitude(), RPGraph::GraphLayout::moveNode(), normalize(), operator*(), operator+(), RPGraph::Coordinate::operator+(), operator+=(), RPGraph::Coordinate::operator+=(), operator-(), and operator/().
The documentation for this class was generated from the following files:
src/RPCommon.hpp
src/RPCommon.cpp