GPUGraphLayout: RPGraph Namespace Reference
RPGraph Namespace Reference
Classes
class BarnesHutApproximator
class BarnesHutCell
class Coordinate
class CPUForceAtlas2
class CSRUGraph
class CUDAForceAtlas2
class ForceAtlas2
class Graph
class GraphLayout
class LayoutAlgorithm
class Real2DVector
class UGraph
Typedefs
typedef uint32_t nid_t
typedef uint32_t eid_t
Functions
float get_random (float lowerbound, float upperbound)
float distance (Coordinate from, Coordinate to)
float distance2 (Coordinate from, Coordinate to)
Real2DVector normalizedDirection (Coordinate from, Coordinate to)
Real2DVector direction (Coordinate from, Coordinate to)
Detailed Description
Common to CPU and GPU implementations.
Which classes does this file rely on? What about the GPU version?
Most of the methods on the GraphLayout class seem to be associated with the CPU implementation, and not the GPU.
Typedef Documentation
nid_t
typedef uint32_t RPGraph::nid_t
Definition at line 35 of file RPGraph.hpp.
eid_t
typedef uint32_t RPGraph::eid_t
Definition at line 39 of file RPGraph.hpp.
Function Documentation
get_random()
float RPGraph::get_random (float lowerbound, float upperbound)
Definition at line 44 of file RPCommon.cpp.
     {
         // https://stackoverflow.com/questions/103512/why-use-static-castintx-instead-of-intx
         // static_cast is used to specify exactly which type of casting we want to do.  static_cast is generally safe.
         return lowerbound + (upperbound-lowerbound) * static_cast <float> (random()) / static_cast <float> (RAND_MAX);
     }
Referenced by RPGraph::GraphLayout::randomizePositions().
distance()
float RPGraph::distance (Coordinate from, Coordinate to)
Definition at line 198 of file RPCommon.cpp.
     {
         const float dx = from.x - to.x;
         const float dy = from.y - to.y;
         return std::sqrt(dx*dx + dy*dy);
     }
References RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by RPGraph::CPUForceAtlas2::apply_repulsion().
distance2()
float RPGraph::distance2 (Coordinate from, Coordinate to)
Definition at line 205 of file RPCommon.cpp.
     {
         const float dx = from.x - to.x;
         const float dy = from.y - to.y;
         return dx*dx + dy*dy;
     }
References RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by RPGraph::BarnesHutApproximator::approximateForce().
normalizedDirection()
Real2DVector RPGraph::normalizedDirection (Coordinate from, Coordinate to)
Definition at line 212 of file RPCommon.cpp.
     {
         const float dx = from.x - to.x;
         const float dy = from.y - to.y;
         const float len = std::sqrt(dx*dx + dy*dy);
         return Real2DVector(dx/len, dy/len);
     }
References RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
direction()
Real2DVector RPGraph::direction (Coordinate from, Coordinate to)
Definition at line 220 of file RPCommon.cpp.
     {
         const float dx = from.x - to.x;
         const float dy = from.y - to.y;
         return Real2DVector(dx, dy);
     }
References RPGraph::Coordinate::x, and RPGraph::Coordinate::y.
Referenced by RPGraph::BarnesHutApproximator::approximateForce().