GPUGraphLayout: src/RPCommon.hpp File Reference
RPCommon.hpp File Reference
Classes
class RPGraph::Real2DVector
class RPGraph::Coordinate
Namespaces
RPGraph
Functions
bool is_file_exists (const char *filename)
float RPGraph::get_random (float lowerbound, float upperbound)
float RPGraph::distance (Coordinate from, Coordinate to)
float RPGraph::distance2 (Coordinate from, Coordinate to)
Real2DVector RPGraph::normalizedDirection (Coordinate from, Coordinate to)
Real2DVector RPGraph::direction (Coordinate from, Coordinate to)
Function Documentation
is_file_exists()
bool is_file_exists (const char * filename)
Definition at line 32 of file RPCommon.cpp.
 {
     std::ifstream infile(filename);
     return infile.good();
 }
Referenced by main(), RPGraph::GraphLayout::writeToBin(), and RPGraph::GraphLayout::writeToCSV().