GPUGraphLayout: src/RPCommon.cpp File Reference
RPCommon.cpp File Reference
#include "RPCommon.hpp"
#include <stdlib.h>
#include <cmath>
#include <fstream>
Namespaces
RPGraph
Functions
bool is_file_exists (const char *filename)
float RPGraph::get_random (float lowerbound, float upperbound)
float RPGraph::distance (Coordinate from, Coordinate to)
float RPGraph::distance2 (Coordinate from, Coordinate to)
Real2DVector RPGraph::normalizedDirection (Coordinate from, Coordinate to)
Real2DVector RPGraph::direction (Coordinate from, Coordinate to)
Function Documentation
is_file_exists()
bool is_file_exists (const char * filename)
Definition at line 32 of file RPCommon.cpp.
Referenced by main(), RPGraph::GraphLayout::writeToBin(), and RPGraph::GraphLayout::writeToCSV().
 {
     std::ifstream infile(filename);
     return infile.good();
 }